#!/usr/bin/env python
#
#  Copyright 2014 - 2016 The BCE Authors. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the license.txt file.
#

MEXP_UNRECOGNIZED_TOKEN = "PE.MEXP.UNRECOGNIZED_TOKEN"
MEXP_DUPLICATED_DECIMAL_DOT = "PE.MEXP.DUPLICATED_DECIMAL_DOT"
MEXP_USE_PROTECTED_HEADER = "PE.MEXP.USE_PROTECTED_HEADER"
MEXP_MISSING_OPERAND = "PE.MEXP.MISSING_OPERAND"
MEXP_MISSING_OPERATOR = "PE.MEXP.MISSING_OPERATOR"
MEXP_FUNCTION_UNSUPPORTED = "PE.MEXP.FUNCTION_UNSUPPORTED"
MEXP_FUNCTION_ARGUMENT_COUNT_MISMATCH = "PE.MEXP.FUNCTION_ARGC_MISMATCH"
MEXP_NO_CONTENT = "PE.MEXP.NO_CONTENT"
MEXP_PARENTHESIS_MISMATCH = "PE.MEXP.PARENTHESIS_MISMATCH"
MEXP_ILLEGAL_ARGUMENT_SEPARATOR = "PE.MEXP.ILLEGAL_ARG_SEPARATOR"
MEXP_RPN_EVALUATION_DIVIDE_ZERO = "PE.MEXP.RPN_EVALUATOR.DIVIDE_ZERO"
MEXP_RPN_EVALUATION_DOMAIN_OUT_OF_RANGE = "PE.MEXP.RPN_EVALUATOR.DOMAIN_OUT_OF_RANGE"
