#!/usr/bin/env python
#
#  Copyright 2014 - 2016 The BCE Authors. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the license.txt file.
#

MOLECULE_UNRECOGNIZED_TOKEN = "PE.ML.UNRECOGNIZED_TOKEN"
MOLECULE_PARENTHESIS_MISMATCH = "PE.ML.PARENTHESIS_MISMATCH"
MOLECULE_NO_CONTENT = "PE.ML.NO_CONTENT"
MOLECULE_UNEXPECTED_TOKEN = "PE.ML.UNEXPECTED_TOKEN"
MOLECULE_DOMAIN_ERROR = "PE.ML.DOMAIN_ERROR"
MOLECULE_EXCEED_OPERAND = "PE.ML.EXCEED_OPERAND"
MOLECULE_ELEMENT_ELIMINATED = "PE.ML.ELEMENT_ELIMINATED"
MOLECULE_UNSUPPORTED_ABBREVIATION = "PE.ML.UNSUPPORTED_ARV"
