#!/usr/bin/env python
#
#  Copyright 2014 - 2016 The BCE Authors. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the license.txt file.
#

CEXP_NO_CONTENT = "PE.CE.NO_CONTENT"
CEXP_DUPLICATED_EQUAL_SIGN = "PE.CE.DUPLICATED_EQUAL_SIGN"
CEXP_MIXED_FORM = "PE.CE.MIXED_FORM"
CEXP_ONLY_ONE_MOLECULE = "PE.CE.ONLY_ONE_MOLECULE"
CEXP_NO_EQUAL_SIGN = "PE.CE.NO_EQUAL_SIGN"
CEXP_EMPTY_EXPRESSION = "PE.CE.EMPTY_EXPRESSION"
CEXP_AUTO_CORRECTION_DISABLED = "PE.CE.AUTO_CORRECTION_DISABLED"
CEXP_PARENTHESIS_MISMATCH = "PE.CE.PARENTHESIS_MISMATCH"
